language: java
jdk:
  - openjdk11

# master 브랜치에 적용
branches:
  only:
    - master


#Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install: "chmod +x ./gradlew"

script: "./gradlew clean build"

#CI 실행완료시 메일알림
notifications:
  email:
    recipients:
      - kyhwesaq@gmail.com

before_deploy:
  - zip -r bootjpa *
  - mkdir -p deploy
  - mv bootjpa.zip deply/bootjpa.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis에서 설정한 값
  secret_access_key: $AWS_SECRET_KEY
  bucket: bootjpa # s3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: private # zip 파일접근을 private권한으로,
  local_dir: deploy # before_deploy에서 생성한 디렉토리

